name: API CI

on:
  push:
    branches: [development]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [development]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  api-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint API
        run: echo "No lint script yet"

      - name: Build API
        run: npm run build:api

      - name: Test API
        run: echo "No tests yet"

